###############################################################################
#
# Copyright (C) 2026 Carlos Schrupp
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
###############################################################################

from .api import (
    DatasetBuilder,
    LogBuilder,
    ProgrammaticLogSpec,
    SectionBuilder,
    build_documents,
    create_dataset,
    document_from_dict,
    document_from_yaml,
    document_to_dict,
    document_to_yaml,
    load_document_yaml,
    load_report,
    render_png_bytes,
    render_report,
    render_section,
    render_section_png,
    render_svg_bytes,
    render_track,
    render_track_png,
    render_window,
    render_window_png,
    report_from_dict,
    report_from_yaml,
    report_to_dict,
    report_to_yaml,
    save_document,
    save_report,
)
from .errors import DatasetValidationError
from .layout import LayoutEngine
from .logfile import (
    LogFileSpec,
    build_document_for_logfile,
    build_documents_for_logfile,
    load_dataset_for_logfile,
    load_datasets_for_logfile,
    load_logfile,
    logfile_from_mapping,
)
from .logfile_schema import get_logfile_json_schema, validate_logfile_mapping
from .model import (
    AnnotationArrowSpec,
    AnnotationGlyphSpec,
    AnnotationIntervalSpec,
    AnnotationLabelMode,
    AnnotationMarkerSpec,
    AnnotationTextSpec,
    ArrayChannel,
    CurveCalloutSpec,
    CurveElement,
    CurveFillBaselineSpec,
    CurveFillCrossoverSpec,
    CurveFillKind,
    CurveFillSpec,
    CurveHeaderDisplaySpec,
    DepthAxisSpec,
    FooterSpec,
    GridDisplayMode,
    GridScaleKind,
    GridSpacingMode,
    GridSpec,
    HeaderField,
    HeaderSpec,
    LogDocument,
    MarkerSpec,
    PageSpec,
    RasterChannel,
    RasterElement,
    ReferenceCurveOverlayMode,
    ReferenceCurveOverlaySpec,
    ReferenceCurveTickSide,
    ReferenceEventSpec,
    ReportBlockSpec,
    ReportDetailCellSpec,
    ReportDetailColumnSpec,
    ReportDetailKind,
    ReportDetailRowSpec,
    ReportDetailSpec,
    ReportFieldSpec,
    ReportServiceTitleSpec,
    ReportValueSpec,
    ScalarChannel,
    ScaleKind,
    ScaleSpec,
    StyleSpec,
    TrackHeaderObjectKind,
    TrackHeaderObjectSpec,
    TrackHeaderSpec,
    TrackKind,
    TrackSpec,
    WellDataset,
    ZoneSpec,
)
from .pipeline import render_from_logfile
from .templates import document_from_mapping, load_document

__all__ = [
    "ArrayChannel",
    "AnnotationArrowSpec",
    "AnnotationGlyphSpec",
    "AnnotationIntervalSpec",
    "AnnotationLabelMode",
    "AnnotationMarkerSpec",
    "AnnotationTextSpec",
    "CurveCalloutSpec",
    "DatasetBuilder",
    "DatasetValidationError",
    "LogBuilder",
    "ProgrammaticLogSpec",
    "CurveElement",
    "CurveFillBaselineSpec",
    "CurveFillCrossoverSpec",
    "CurveFillKind",
    "CurveFillSpec",
    "CurveHeaderDisplaySpec",
    "DepthAxisSpec",
    "FooterSpec",
    "GridDisplayMode",
    "GridScaleKind",
    "GridSpacingMode",
    "GridSpec",
    "HeaderField",
    "HeaderSpec",
    "LayoutEngine",
    "LogFileSpec",
    "LogDocument",
    "MarkerSpec",
    "PageSpec",
    "RasterChannel",
    "RasterElement",
    "ReportBlockSpec",
    "ReportDetailCellSpec",
    "ReportDetailColumnSpec",
    "ReportDetailKind",
    "ReportDetailRowSpec",
    "ReportDetailSpec",
    "ReportFieldSpec",
    "ReportServiceTitleSpec",
    "ReportValueSpec",
    "ReferenceCurveOverlayMode",
    "ReferenceCurveOverlaySpec",
    "ReferenceCurveTickSide",
    "ReferenceEventSpec",
    "ScaleKind",
    "ScaleSpec",
    "ScalarChannel",
    "StyleSpec",
    "TrackHeaderObjectKind",
    "TrackHeaderObjectSpec",
    "TrackHeaderSpec",
    "TrackKind",
    "TrackSpec",
    "WellDataset",
    "ZoneSpec",
    "SectionBuilder",
    "build_documents",
    "build_document_for_logfile",
    "build_documents_for_logfile",
    "document_from_dict",
    "document_from_yaml",
    "document_to_dict",
    "document_to_yaml",
    "load_document_yaml",
    "load_datasets_for_logfile",
    "load_dataset_for_logfile",
    "load_logfile",
    "load_report",
    "logfile_from_mapping",
    "get_logfile_json_schema",
    "validate_logfile_mapping",
    "render_from_logfile",
    "report_from_dict",
    "report_from_yaml",
    "report_to_dict",
    "report_to_yaml",
    "save_document",
    "save_report",
    "render_png_bytes",
    "render_report",
    "render_section",
    "render_section_png",
    "render_svg_bytes",
    "render_track",
    "render_track_png",
    "render_window",
    "render_window_png",
    "create_dataset",
    "document_from_mapping",
    "load_document",
]

__version__ = "0.1.0"
